
org:
  mik:
    task:
      kafka:
        bootstrap-servers: 192.168.59.103:9092
        consumer:
          group-id: spring-homework-task-status
          max-poll-records: 10
          auto-offset-reset: "earliest"
        topics:
          task_status_change: spring_homework_task_change_status
          task_status_change_error: spring_homework_task_change_status_error